
import { db } from '@/firebaseDB';
export const createUserData = {
    data(){
        return{
            allApps:[
                {
                    id:0,
                    positionInList:null,
                    title:'Calcualtor',
                    appName:'calculator',
                    favorite:{
                        id:null,
                        added:false,
                    },
                    iconURL:"http://cdn.haba.usermd.net/os/icons/apps/calculator.svg",
                    emitToApp:'osAppRun-calculator',
                    pinned:true,
                },
                {
                    id:1,
                    positionInList:null,
                    title:'Music',
                    appName:'music',
                    widget:{
                        id:null,
                        component: 'widgetMusic',
                        ready:'',
                        show:true
                    },
                    favorite:{
                        id:null,
                        added:false,
                    },
                    iconURL:"http://cdn.haba.usermd.net/os/icons/apps/music.svg",
                    emitToApp:'osAppRun-music',
                    pinned:true,
                },
                {
                    id:2,
                    positionInList:null,
                    title:'Weather',
                    appName:'weather',
                    widget:{
                        id:null,
                        component: 'widgetWeather',
                        ready:'',
                        show:true
                    },
                    favorite:{
                        id:null,
                        added:true,
                    },
                    iconURL:"http://cdn.haba.usermd.net/os/icons/apps/weather.svg",
                    emitToApp:'osAppRun-weather',
                    pinned:true,
                },
                {
                    id:3,
                    positionInList:null,
                    title:'Calendar',
                    appName:'calendar',
                    favorite:{
                        id:null,
                        added:false,
                    },
                    iconURL:"http://cdn.haba.usermd.net/os/icons/apps/calendar.svg",
                    emitToApp:'osAppRun-calendar',
                    pinned:true,
                },
                {
                    id:4,
                    positionInList:null,
                    title:'Bookmarks',
                    appName:'bookmark',
                    widget:{
                        id:null,
                        component: 'widgetBookmark',
                        ready:'',
                        show:true
                    },
                    favorite:{
                        id:null,
                        added:true,
                    },
                    iconURL:"http://cdn.haba.usermd.net/os/icons/apps/bookmark.svg",
                    emitToApp:'osAppRun-bookmark',
                    pinned:true,
                },
            ],
        }
    },
    methods:{
        createTreeData(user){
            console.log(user);
            let empty = true
            db.collection(user).get()
            .then((data)=>{
                empty = data.empty
            })
            if(!empty){
                console.log('run');
                let docsName = ['system','todoApp','bookmarkApp','musicPlayer']
                let dummy = {dummy:'dummy'}
                docsName.forEach((docName)=>{
                    db.collection(user).doc(docName).set({dummy})
                })
                this.createAllAppDataInDB(db.collection(user).doc('system'))
            }
        },
        createAllAppDataInDB(systemPathToDB){
            createUserData.data().allApps.forEach((item,index)=>{
                systemPathToDB.collection('allApp').doc(index.toString()).set(item)
            })
        }
    }
}